api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix: /blog
app:
    resource: '@AppBundle/Controller/'
    type: annotation

